export const HEALTH_RULES = {
  ZERO_RECORDS: true,
  VALIDATION_FAILURE_RATE: 0.3,
  RECORD_COUNT_DROP_RATIO: 0.5,
  BASELINE_RUN_COUNT: 5,
  MIN_BASELINE_RUNS: 2,
  MOSTLY_INVALID_VALID_RATE: 0.1,
} as const;
